### ISSUE TITLE
PRACTICA 2 "RELACIONES" EQUIPO: EDUARDO TOMAS FERIA ORTIZ 1AS

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/practica-de-relaciones-team-eduardo-tomas-1as#1]
[PRACTICA2_2U_RELACIONES_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-relaciones-team-eduardo-tomas-1as/files/7318498/PRACTICA2_2U_RELACIONES_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf)

**Comment by lucero012** [comment]
de acuerdo a los criterios de evolución le damos le 16% porque en los ejercicios de relación  de conjuntos pusieron pares ordenados que no van , no describen el procedimiento ni justifican los resultados

**Comment by josealfredo79** [comment]
Para la próxima no se registra calificación

**Comment by josealfredo79** [comment]
Revisado.
